version: "3.7"

services:
  mario:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: mario
    restart: always
    # depends_on:
    #   - redis
    ports:
      - "8080:8080"
    volumes:
      - ./:/app

volumes:
  red_data: {}
